### PR TITLE
adding Julia chapter

### PR DESCRIPTION
**Pull request by gaelforget**
In this PR :

- [move Julia intro session to Mon, as discussed. 1h wont be too long](https://github.com/ECCO-Hackweek/ecco-2024/pull/84/commits/0d73a575447dd926a983c4b13f330d5c040dcbd6)
- [this draft chapter](https://github.com/ECCO-Hackweek/ecco-2024/pull/84/commits/a8a4b20416dab6468c0bf74314fc64c3562d3288) is a bit of a placeholder; with content to be refined
- I have tried but failed to build locally the book ; See https://github.com/ECCO-Hackweek/ecco-2024/discussions/34#discussioncomment-10879381 (does GitHub action do it for us?)
- draft notebooks : `guidelines.ipynb`, `MITgcm_test_run.ipynb`, `ECCO_diagnostics.ipynb`, `ArgoData.ipynb`
- [add minimal setup_modules.csh](https://github.com/ECCO-Hackweek/ecco-2024/pull/84/commits/e66f57c792acb6d3066d0bf071ee80ad3e131165) that should suffice for this activity

### CODE REVIEW

**Comment by gaelforget** [comment]
this error occurs [here](https://productionresultssa1.blob.core.windows.net/actions-results/2d497da6-9709-4826-b296-38de39db5ef5/workflow-job-run-657a34c5-4ed6-57bb-351e-9b38cba104b9/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-10-08T12%3A09%3A00Z&sig=ul77UqoE83dUBGRP5xbPeGSx%2BfDqOie9lF%2BkSjBGBFE%3D&ske=2024-10-08T20%3A06%3A47Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2024-10-08T08%3A06%3A47Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2024-08-04&sp=r&spr=https&sr=b&st=2024-10-08T11%3A58%3A55Z&sv=2024-08-04)

```
/home/runner/work/ecco-2024/ecco-2024/book/tutorials/Julia_setup/MITgcm_test_run.ipynb:10002: WARNING: Document headings start at H2, not H1 [myst.header]
/home/runner/work/ecco-2024/ecco-2024/book/tutorials/Julia_setup/guidelines.ipynb:10003: WARNING: Document headings start at H2, not H1 [myst.header]
/home/runner/work/ecco-2024/ecco-2024/book/tutorials/Julia_setup/guidelines.ipynb:10016: WARNING: Document headings start at H2, not H1 [myst.header]
looking for now-outdated files... none found
```

how to fix this?

**Comment by gaelforget** [comment]
can this be merged? 

so I can visualize the result @ https://ecco-hackweek.github.io/ecco-2024/

ps. was not able to build book , see https://github.com/ECCO-Hackweek/ecco-2024/discussions/34#discussioncomment-10879381

**Comment by gaelforget** [comment]
Hi @ifenty , can you or someone else with merge PR privileges please review this PR?

**Comment by gaelforget** [comment]
> Hi @ifenty , can you or someone else with merge PR privileges please review this PR?

- I have now verified that the book compiles without issue. See https://gaelforget.github.io/ecco-2024/tutorials/Julia_setup_index.html
- would be good if this could be merged soon if possible. Will use the same branch later to send updates if that works

**Comment by ifenty** [comment]
@gaelforget added you as admin.  please make sure book compiles locally before PR

**Pull request merged**
